controller_list:
  - name: fake_thumb_controller
    type: $(arg execution_type)
    joints:
      - t_mcp_pitch
      - t_mcp_yaw
      - t_pip_pitch
  - name: fake_index_controller
    type: $(arg execution_type)
    joints:
      - i_mcp_yaw
      - i_mcp_pitch
      - i_pip_pitch
      - i_dip_pitch
  - name: fake_middle_controller
    type: $(arg execution_type)
    joints:
      - m_mcp_yaw
      - m_mcp_pitch
      - m_pip_pitch
      - m_dip_pitch
  - name: fake_ring_controller
    type: $(arg execution_type)
    joints:
      - r_mcp_yaw
      - r_mcp_pitch
      - r_pip_pitch
      - r_dip_pitch
  - name: fake_small_controller
    type: $(arg execution_type)
    joints:
      - s_mcp_yaw
      - s_mcp_pitch
      - s_pip_pitch
      - s_dip_pitch
initial:  # Define initial robot poses.
  - group: thumb
    pose: victory
  - group: middle
    pose: spider man